import '../styles/globals.css'
import type { AppProps } from 'next/app'
import React, { useEffect } from 'react'
import Head from 'next/head'
import { CssBaseline, ThemeProvider } from '@material-ui/core'
import theme from '../styles/theme'
import { Navbar } from '../components/navbar'
import getConfig from 'next/config'

const { publicRuntimeConfig } = getConfig()
const liffId = publicRuntimeConfig?.liffID

function MyApp({ Component, pageProps }: AppProps) {
  useEffect(() => {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector('#jss-server-side')
    if (jssStyles) {
      jssStyles?.parentElement?.removeChild(jssStyles)
    }

    async function connectWithLiff() {
      if (!liffId) {
        throw Error('Please add DEVELOPMENT_LIFF_ENV into .env.local')
      }

      const liff = (await import('@line/liff')).default
      try {
        await liff.init({ liffId })
      } catch (error) {
        console.error('liff init error', error.message)
      }
      if (!liff.isLoggedIn()) {
        liff.login({ redirectUri: window.location.href })
      }
    }
    connectWithLiff()
  }, [])

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <Navbar />
      <Component {...pageProps} />
    </ThemeProvider>
  )
}
export default MyApp
