export const covidTestCentres = [
  {
    id: 1,
    name: 'เสนานิคม 2 ชายคลอง',
    district: 'จตุจักร',
    subdistrict: 'เสนานิคม',
    capacity: 750,
  },
  {
    id: 2,
    name: 'ลานหลัง สน.ดินแดง',
    district: 'ดินแดง',
    subdistrict: 'รัชดาภิเษก',
    capacity: 1000,
  },
  {
    id: 3,
    name: 'ชุมชนท่าน้ำสามเสน',
    district: 'ดุสิต',
    subdistrict: 'วชิรพยาบาล',
    capacity: 1000,
  },
  {
    id: 4,
    name: 'พระราม 2 ซอย 92',
    district: 'บางขุนเทียน',
    subdistrict: 'แสมดำ',
    capacity: 1000,
  },
  {
    id: 5,
    name: 'วัดไผ่เงิน',
    district: 'บางคอแหลม',
    subdistrict: '',
    capacity: 300,
    '': '',
  },
  {
    id: 6,
    name: 'วัดบางนาใน',
    district: 'บางนา',
    subdistrict: 'บางนา',
    capacity: 700,
  },
  {
    id: 7,
    name: 'สหกรณ์เคหสถานบ้านมั่นคงวิมานทอง จำกัด',
    district: 'บางบอน',
    subdistrict: '',
    capacity: 400,
  },
  {
    id: 8,
    name: 'วัดพิชัย',
    district: 'บึงกุ่ม',
    subdistrict: 'คลองกุ่ม',
    capacity: 1000,
  },
  {
    id: 9,
    name: 'อ่อนนุช 84',
    district: 'ประเวศ',
    subdistrict: 'ประเวศ',
    capacity: 800,
  },
  {
    id: 10,
    name: 'ลานจอดรถบริษัทนามีบุค จำกัด',
    district: 'พระโขนง',
    subdistrict: '',
    capacity: 400,
  },
  {
    id: 11,
    name: 'วัดจันทร์ประดิษฐาราม',
    district: 'ภาษีเจริญ',
    subdistrict: '',
    capacity: 300,
  },
  {
    id: 12,
    name: 'ลานกีฬามัสยิดอัตตั๊กวา',
    district: 'มีนบุรี',
    subdistrict: 'มีนบุรี / แสนแสบ',
    capacity: 800,
  },
  {
    id: 13,
    name: 'ชุมชนริมทางรถไฟมักกะสัน',
    district: 'ราชเทวี',
    subdistrict: 'มักกะสัน',
    capacity: 1000,
  },
  {
    id: 14,
    name: 'สวนพญาไท',
    district: 'พญาไท',
    subdistrict: 'พญาไท',
    capacity: 1000,
  },
  {
    id: 15,
    name: 'วัดลาดปลาเค้า',
    district: 'ลาดพร้าว',
    subdistrict: 'จรเข้บัว',
    capacity: 1000,
  },
  {
    id: 16,
    name: 'เสนานิคม 2',
    district: 'ลาดพร้าว',
    subdistrict: 'จรเข้บัว',
    capacity: 2000,
  },
  {
    id: 17,
    name: ' ตลาดสะพาน 2',
    district: 'วังทองหลาง',
    subdistrict: 'สะพานสอง',
    capacity: 1000,
  },
  {
    id: 18,
    name: 'โรงเรียนพิบูลย์อุปถัมภ์',
    district: 'ห้วยขวาง',
    subdistrict: 'สามเสนนอก',
    capacity: 1000,
  },
  {
    id: 19,
    name: 'วัดหนัง',
    district: 'จอมทอง',
    subdistrict: '',
    capacity: 5000,
  },
  {
    id: 20,
    name: 'ตลาดคุ้มบางกะเจ้า',
    district: 'พระประแดง',
    subdistrict: '',
    capacity: 900,
  },
  {
    id: 21,
    name: 'วัดวงษ์ลาภาราม เลขที่ 79 ซอยเพชรเกษม 106',
    district: 'หนองแขม',
    subdistrict: '',
    capacity: 0,
  },
  {
    id: 22,
    name: 'ชุมชนนาคสถาพร 1 ซอยเพชรเกษม 69 แยก 6-2-7',
    district: 'หนองแขม',
    subdistrict: '',
    capacity: 0,
  },
  {
    id: 23,
    name: 'วัดสะแกงาม ถนนสะแกงาม ซ. 28',
    district: 'บางขุนเทียน',
    subdistrict: 'แสมดำ',
    capacity: 0,
  },
  {
    id: 24,
    name: 'ลานหน้าชุมชน ซอยเพชรเกษม 62/1',
    district: 'บางแค',
    subdistrict: 'บางแคเหนือ',
    capacity: 0,
  },
  {
    id: 25,
    name: 'ตลาดนัดสองคุณจ่า บางแคซอย 4',
    district: 'บางแค',
    subdistrict: 'บางแค',
    capacity: 0,
  },
  {
    id: 26,
    name: 'วัดชัยฉิมพลี ซ.บางแวก 71',
    district: 'ภาษีเจริญ',
    subdistrict: 'บางแวก',
    capacity: 0,
  },
  {
    id: 27,
    name: 'มัสยิดเนี๊ยะมาตุลมักบูลีน (สุเหร่าแบนใหญ่)',
    district: 'หนองจอก',
    subdistrict: 'โคกแฝก',
    capacity: 300,
  },
]
