export const covidTestCentres = {
  '1': {
    ID: 1,
    name: 'เสนานิคม 2 ชายคลอง',
    district: 'จตุจักร',
    subdistrict: 'เสนานิคม',
    capacity: 750,
  },
  '2': {
    ID: 2,
    name: 'ลานหลัง สน.ดินแดง',
    district: 'ดินแดง',
    subdistrict: 'รัชดาภิเษก',
    capacity: 1000,
  },
  '3': {
    ID: 3,
    name: 'ชุมชนท่าน้ำสามเสน',
    district: 'ดุสิต',
    subdistrict: 'วชิรพยาบาล',
    capacity: 1000,
  },
  '4': {
    ID: 4,
    name: 'พระราม 2 ซอย 92',
    district: 'บางขุนเทียน',
    subdistrict: 'แสมดำ',
    capacity: 1000,
  },
  '5': {
    ID: 5,
    name: 'วัดไผ่เงิน',
    district: 'บางคอแหลม',
    subdistrict: '',
    capacity: 300,
    '': '',
  },
  '6': {
    ID: 6,
    name: 'วัดบางนาใน',
    district: 'บางนา',
    subdistrict: 'บางนา',
    capacity: 700,
  },
  '7': {
    ID: 7,
    name: 'สหกรณ์เคหสถานบ้านมั่นคงวิมานทอง จำกัด',
    district: 'บางบอน',
    subdistrict: '',
    capacity: 400,
  },
  '8': {
    ID: 8,
    name: 'วัดพิชัย',
    district: 'บึงกุ่ม',
    subdistrict: 'คลองกุ่ม',
    capacity: 1000,
  },
  '9': {
    ID: 9,
    name: 'อ่อนนุช 84',
    district: 'ประเวศ',
    subdistrict: 'ประเวศ',
    capacity: 800,
  },
  '10': {
    ID: 10,
    name: 'ลานจอดรถบริษัทนามีบุค จำกัด',
    district: 'พระโขนง',
    subdistrict: '',
    capacity: 400,
  },
  '11': {
    ID: 11,
    name: 'วัดจันทร์ประดิษฐาราม',
    district: 'ภาษีเจริญ',
    subdistrict: '',
    capacity: 300,
  },
  '12': {
    ID: 12,
    name: 'ลานกีฬามัสยิดอัตตั๊กวา',
    district: 'มีนบุรี',
    subdistrict: 'มีนบุรี / แสนแสบ',
    capacity: 800,
  },
  '13': {
    ID: 13,
    name: 'ชุมชนริมทางรถไฟมักกะสัน',
    district: 'ราชเทวี',
    subdistrict: 'มักกะสัน',
    capacity: 1000,
  },
  '14': {
    ID: 14,
    name: 'สวนพญาไท',
    district: 'พญาไท',
    subdistrict: 'พญาไท',
    capacity: 1000,
  },
  '15': {
    ID: 15,
    name: 'วัดลาดปลาเค้า',
    district: 'ลาดพร้าว',
    subdistrict: 'จรเข้บัว',
    capacity: 1000,
  },
  '16': {
    ID: 16,
    name: 'เสนานิคม 2',
    district: 'ลาดพร้าว',
    subdistrict: 'จรเข้บัว',
    capacity: 2000,
  },
  '17': {
    ID: 17,
    name: ' ตลาดสะพาน 2',
    district: 'วังทองหลาง',
    subdistrict: 'สะพานสอง',
    capacity: 1000,
  },
  '18': {
    ID: 18,
    name: 'โรงเรียนพิบูลย์อุปถัมภ์',
    district: 'ห้วยขวาง',
    subdistrict: 'สามเสนนอก',
    capacity: 1000,
  },
  '19': {
    ID: 19,
    name: 'วัดหนัง',
    district: 'จอมทอง',
    subdistrict: '',
    capacity: 5000,
  },
  '20': {
    ID: 20,
    name: 'ตลาดคุ้มบางกะเจ้า',
    district: 'พระประแดง',
    subdistrict: '',
    capacity: 900,
  },
  '21': {
    ID: 21,
    name: 'วัดวงษ์ลาภาราม เลขที่ 79 ซอยเพชรเกษม 106',
    district: 'หนองแขม',
    subdistrict: '',
    capacity: 0,
  },
  '22': {
    ID: 22,
    name: 'ชุมชนนาคสถาพร 1 ซอยเพชรเกษม 69 แยก 6-2-7',
    district: 'หนองแขม',
    subdistrict: '',
    capacity: 0,
  },
  '23': {
    ID: 23,
    name: 'วัดสะแกงาม ถนนสะแกงาม ซ. 28',
    district: 'บางขุนเทียน',
    subdistrict: 'แสมดำ',
    capacity: 0,
  },
  '24': {
    ID: 24,
    name: 'ลานหน้าชุมชน ซอยเพชรเกษม 62/1',
    district: 'บางแค',
    subdistrict: 'บางแคเหนือ',
    capacity: 0,
  },
  '25': {
    ID: 25,
    name: 'ตลาดนัดสองคุณจ่า บางแคซอย 4',
    district: 'บางแค',
    subdistrict: 'บางแค',
    capacity: 0,
  },
  '26': {
    ID: 26,
    name: 'วัดชัยฉิมพลี ซ.บางแวก 71',
    district: 'ภาษีเจริญ',
    subdistrict: 'บางแวก',
    capacity: 0,
  },
  '27': {
    ID: 27,
    name: 'มัสยิดเนี๊ยะมาตุลมักบูลีน (สุเหร่าแบนใหญ่)',
    district: 'หนองจอก',
    subdistrict: 'โคกแฝก',
    capacity: 300,
  },
}
